/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.devinbox.client.api;

import io.devinbox.client.ApiClient;
import io.devinbox.client.ApiException;
import io.devinbox.client.ApiResponse;
import io.devinbox.client.Configuration;
import io.devinbox.client.Pair;

import io.devinbox.client.model.GetMessagesSkipParameter;
import io.devinbox.client.model.MessageCountResult;
import io.devinbox.client.model.MessageParsedViewModel;
import io.devinbox.client.model.MessageViewModel;
import io.devinbox.client.model.MessagesViewModel;
import io.devinbox.client.model.ProblemDetails;
import java.util.UUID;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.InputStream;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.net.http.HttpRequest;
import java.nio.channels.Channels;
import java.nio.channels.Pipe;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

import java.util.ArrayList;
import java.util.StringJoiner;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Consumer;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-29T16:01:12.920188793Z[Etc/UTC]", comments = "Generator version: 7.18.0")
public class MessagesApi {
  /**
   * Utility class for extending HttpRequest.Builder functionality.
   */
  private static class HttpRequestBuilderExtensions {
    /**
     * Adds additional headers to the provided HttpRequest.Builder. Useful for adding method/endpoint specific headers.
     *
     * @param builder the HttpRequest.Builder to which headers will be added
     * @param headers a map of header names and values to add; may be null
     * @return the same HttpRequest.Builder instance with the additional headers set
     */
    static HttpRequest.Builder withAdditionalHeaders(HttpRequest.Builder builder, Map<String, String> headers) {
        if (headers != null) {
            for (Map.Entry<String, String> entry : headers.entrySet()) {
                builder.header(entry.getKey(), entry.getValue());
            }
        }
        return builder;
    }
  }
  private final HttpClient memberVarHttpClient;
  private final ObjectMapper memberVarObjectMapper;
  private final String memberVarBaseUri;
  private final Consumer<HttpRequest.Builder> memberVarInterceptor;
  private final Duration memberVarReadTimeout;
  private final Consumer<HttpResponse<InputStream>> memberVarResponseInterceptor;
  private final Consumer<HttpResponse<InputStream>> memberVarAsyncResponseInterceptor;

  public MessagesApi() {
    this(Configuration.getDefaultApiClient());
  }

  public MessagesApi(ApiClient apiClient) {
    memberVarHttpClient = apiClient.getHttpClient();
    memberVarObjectMapper = apiClient.getObjectMapper();
    memberVarBaseUri = apiClient.getBaseUri();
    memberVarInterceptor = apiClient.getRequestInterceptor();
    memberVarReadTimeout = apiClient.getReadTimeout();
    memberVarResponseInterceptor = apiClient.getResponseInterceptor();
    memberVarAsyncResponseInterceptor = apiClient.getAsyncResponseInterceptor();
  }


  protected ApiException getApiException(String operationId, HttpResponse<InputStream> response) throws IOException {
    InputStream responseBody = ApiClient.getResponseBody(response);
    String body = null;
    try {
      body = responseBody == null ? null : new String(responseBody.readAllBytes());
    } finally {
      if (responseBody != null) {
        responseBody.close();
      }
    }
    String message = formatExceptionMessage(operationId, response.statusCode(), body);
    return new ApiException(response.statusCode(), message, response.headers(), body);
  }

  private String formatExceptionMessage(String operationId, int statusCode, String body) {
    if (body == null || body.isEmpty()) {
      body = "[no body]";
    }
    return operationId + " call failed with: " + statusCode + " - " + body;
  }

  /**
   * Download file from the given response.
   *
   * @param response Response
   * @return File
   * @throws ApiException If fail to read file content from response and write to disk
   */
  public File downloadFileFromResponse(HttpResponse<InputStream> response, InputStream responseBody) throws ApiException {
    if (responseBody == null) {
      throw new ApiException(new IOException("Response body is empty"));
    }
    try {
      File file = prepareDownloadFile(response);
      java.nio.file.Files.copy(responseBody, file.toPath(), java.nio.file.StandardCopyOption.REPLACE_EXISTING);
      return file;
    } catch (IOException e) {
      throw new ApiException(e);
    }
  }

  /**
   * <p>Prepare the file for download from the response.</p>
   *
   * @param response a {@link java.net.http.HttpResponse} object.
   * @return a {@link java.io.File} object.
   * @throws java.io.IOException if any.
   */
  private File prepareDownloadFile(HttpResponse<InputStream> response) throws IOException {
    String filename = null;
    java.util.Optional<String> contentDisposition = response.headers().firstValue("Content-Disposition");
    if (contentDisposition.isPresent() && !"".equals(contentDisposition.get())) {
      // Get filename from the Content-Disposition header.
      java.util.regex.Pattern pattern = java.util.regex.Pattern.compile("filename=['\"]?([^'\"\\s]+)['\"]?");
      java.util.regex.Matcher matcher = pattern.matcher(contentDisposition.get());
      if (matcher.find())
        filename = matcher.group(1);
    }
    File file = null;
    if (filename != null) {
      java.nio.file.Path tempDir = java.nio.file.Files.createTempDirectory("swagger-gen-native");
      java.nio.file.Path filePath = java.nio.file.Files.createFile(tempDir.resolve(filename));
      file = filePath.toFile();
      tempDir.toFile().deleteOnExit();   // best effort cleanup
      file.deleteOnExit(); // best effort cleanup
    } else {
      file = java.nio.file.Files.createTempFile("download-", "").toFile();
      file.deleteOnExit(); // best effort cleanup
    }
    return file;
  }

  /**
   * Get the last message from a mailbox
   * Retrieves the most recent message from the specified mailbox. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @return MessageViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageViewModel getLastMessage(@jakarta.annotation.Nonnull String key) throws ApiException {
    return getLastMessage(key, null);
  }

  /**
   * Get the last message from a mailbox
   * Retrieves the most recent message from the specified mailbox. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @param headers Optional headers to include in the request
   * @return MessageViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageViewModel getLastMessage(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageViewModel> localVarResponse = getLastMessageWithHttpInfo(key, headers);
    return localVarResponse.getData();
  }

  /**
   * Get the last message from a mailbox
   * Retrieves the most recent message from the specified mailbox. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @return ApiResponse&lt;MessageViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageViewModel> getLastMessageWithHttpInfo(@jakarta.annotation.Nonnull String key) throws ApiException {
    return getLastMessageWithHttpInfo(key, null);
  }

  /**
   * Get the last message from a mailbox
   * Retrieves the most recent message from the specified mailbox. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageViewModel> getLastMessageWithHttpInfo(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLastMessageRequestBuilder(key, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLastMessage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageViewModel>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageViewModel responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageViewModel>() {});
        

        return new ApiResponse<MessageViewModel>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLastMessageRequestBuilder(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getLastMessage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}/last"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get the last message with template parsing
   * Retrieves the most recent message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @param template  (required)
   * @return MessageParsedViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageParsedViewModel getLastMessageWithTemplate(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template) throws ApiException {
    return getLastMessageWithTemplate(key, template, null);
  }

  /**
   * Get the last message with template parsing
   * Retrieves the most recent message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @param template  (required)
   * @param headers Optional headers to include in the request
   * @return MessageParsedViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageParsedViewModel getLastMessageWithTemplate(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageParsedViewModel> localVarResponse = getLastMessageWithTemplateWithHttpInfo(key, template, headers);
    return localVarResponse.getData();
  }

  /**
   * Get the last message with template parsing
   * Retrieves the most recent message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @param template  (required)
   * @return ApiResponse&lt;MessageParsedViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageParsedViewModel> getLastMessageWithTemplateWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template) throws ApiException {
    return getLastMessageWithTemplateWithHttpInfo(key, template, null);
  }

  /**
   * Get the last message with template parsing
   * Retrieves the most recent message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox is empty.
   * @param key  (required)
   * @param template  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageParsedViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageParsedViewModel> getLastMessageWithTemplateWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getLastMessageWithTemplateRequestBuilder(key, template, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getLastMessageWithTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageParsedViewModel>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageParsedViewModel responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageParsedViewModel>() {});
        

        return new ApiResponse<MessageParsedViewModel>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getLastMessageWithTemplateRequestBuilder(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getLastMessageWithTemplate");
    }
    // verify the required parameter 'template' is set
    if (template == null) {
      throw new ApiException(400, "Missing the required parameter 'template' when calling getLastMessageWithTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}/{template}/last"
        .replace("{key}", ApiClient.urlEncode(key.toString()))
        .replace("{template}", ApiClient.urlEncode(template.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get a specific message by ID
   * Retrieves a specific message from the specified mailbox using its unique ID.
   * @param key  (required)
   * @param id  (required)
   * @return MessageViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageViewModel getMessageById(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull UUID id) throws ApiException {
    return getMessageById(key, id, null);
  }

  /**
   * Get a specific message by ID
   * Retrieves a specific message from the specified mailbox using its unique ID.
   * @param key  (required)
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return MessageViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageViewModel getMessageById(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageViewModel> localVarResponse = getMessageByIdWithHttpInfo(key, id, headers);
    return localVarResponse.getData();
  }

  /**
   * Get a specific message by ID
   * Retrieves a specific message from the specified mailbox using its unique ID.
   * @param key  (required)
   * @param id  (required)
   * @return ApiResponse&lt;MessageViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageViewModel> getMessageByIdWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull UUID id) throws ApiException {
    return getMessageByIdWithHttpInfo(key, id, null);
  }

  /**
   * Get a specific message by ID
   * Retrieves a specific message from the specified mailbox using its unique ID.
   * @param key  (required)
   * @param id  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageViewModel> getMessageByIdWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMessageByIdRequestBuilder(key, id, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMessageById", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageViewModel>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageViewModel responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageViewModel>() {});
        

        return new ApiResponse<MessageViewModel>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMessageByIdRequestBuilder(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull UUID id, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getMessageById");
    }
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getMessageById");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}/get"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "id";
    localVarQueryParams.addAll(ApiClient.parameterToPairs("id", id));

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get message count for a mailbox
   * Returns the total number of messages in the specified mailbox.
   * @param key  (required)
   * @return MessageCountResult
   * @throws ApiException if fails to make API call
   */
  public MessageCountResult getMessageCount(@jakarta.annotation.Nonnull String key) throws ApiException {
    return getMessageCount(key, null);
  }

  /**
   * Get message count for a mailbox
   * Returns the total number of messages in the specified mailbox.
   * @param key  (required)
   * @param headers Optional headers to include in the request
   * @return MessageCountResult
   * @throws ApiException if fails to make API call
   */
  public MessageCountResult getMessageCount(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageCountResult> localVarResponse = getMessageCountWithHttpInfo(key, headers);
    return localVarResponse.getData();
  }

  /**
   * Get message count for a mailbox
   * Returns the total number of messages in the specified mailbox.
   * @param key  (required)
   * @return ApiResponse&lt;MessageCountResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageCountResult> getMessageCountWithHttpInfo(@jakarta.annotation.Nonnull String key) throws ApiException {
    return getMessageCountWithHttpInfo(key, null);
  }

  /**
   * Get message count for a mailbox
   * Returns the total number of messages in the specified mailbox.
   * @param key  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageCountResult&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageCountResult> getMessageCountWithHttpInfo(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMessageCountRequestBuilder(key, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMessageCount", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageCountResult>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageCountResult responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageCountResult>() {});
        

        return new ApiResponse<MessageCountResult>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMessageCountRequestBuilder(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getMessageCount");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}/count"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get messages from a mailbox
   * Retrieves messages from the specified mailbox with optional pagination. Default: skip&#x3D;0, take&#x3D;10, max take&#x3D;25.
   * @param key  (required)
   * @param skip  (optional)
   * @param take  (optional)
   * @return MessagesViewModel
   * @throws ApiException if fails to make API call
   */
  public MessagesViewModel getMessages(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nullable GetMessagesSkipParameter skip, @jakarta.annotation.Nullable GetMessagesSkipParameter take) throws ApiException {
    return getMessages(key, skip, take, null);
  }

  /**
   * Get messages from a mailbox
   * Retrieves messages from the specified mailbox with optional pagination. Default: skip&#x3D;0, take&#x3D;10, max take&#x3D;25.
   * @param key  (required)
   * @param skip  (optional)
   * @param take  (optional)
   * @param headers Optional headers to include in the request
   * @return MessagesViewModel
   * @throws ApiException if fails to make API call
   */
  public MessagesViewModel getMessages(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nullable GetMessagesSkipParameter skip, @jakarta.annotation.Nullable GetMessagesSkipParameter take, Map<String, String> headers) throws ApiException {
    ApiResponse<MessagesViewModel> localVarResponse = getMessagesWithHttpInfo(key, skip, take, headers);
    return localVarResponse.getData();
  }

  /**
   * Get messages from a mailbox
   * Retrieves messages from the specified mailbox with optional pagination. Default: skip&#x3D;0, take&#x3D;10, max take&#x3D;25.
   * @param key  (required)
   * @param skip  (optional)
   * @param take  (optional)
   * @return ApiResponse&lt;MessagesViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessagesViewModel> getMessagesWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nullable GetMessagesSkipParameter skip, @jakarta.annotation.Nullable GetMessagesSkipParameter take) throws ApiException {
    return getMessagesWithHttpInfo(key, skip, take, null);
  }

  /**
   * Get messages from a mailbox
   * Retrieves messages from the specified mailbox with optional pagination. Default: skip&#x3D;0, take&#x3D;10, max take&#x3D;25.
   * @param key  (required)
   * @param skip  (optional)
   * @param take  (optional)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessagesViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessagesViewModel> getMessagesWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nullable GetMessagesSkipParameter skip, @jakarta.annotation.Nullable GetMessagesSkipParameter take, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getMessagesRequestBuilder(key, skip, take, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getMessages", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessagesViewModel>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessagesViewModel responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessagesViewModel>() {});
        

        return new ApiResponse<MessagesViewModel>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getMessagesRequestBuilder(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nullable GetMessagesSkipParameter skip, @jakarta.annotation.Nullable GetMessagesSkipParameter take, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getMessages");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    List<Pair> localVarQueryParams = new ArrayList<>();
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    localVarQueryParameterBaseName = "skip";
    localVarQueryStringJoiner.add(skip.toUrlQueryString());
    localVarQueryParameterBaseName = "take";
    localVarQueryStringJoiner.add(take.toUrlQueryString());

    if (!localVarQueryParams.isEmpty() || localVarQueryStringJoiner.length() != 0) {
      StringJoiner queryJoiner = new StringJoiner("&");
      localVarQueryParams.forEach(p -> queryJoiner.add(p.getName() + '=' + p.getValue()));
      if (localVarQueryStringJoiner.length() != 0) {
        queryJoiner.add(localVarQueryStringJoiner.toString());
      }
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath + '?' + queryJoiner.toString()));
    } else {
      localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));
    }

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get single message from a mailbox
   * Retrieves a single message from the specified mailbox. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @return MessageViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageViewModel getSingleMessage(@jakarta.annotation.Nonnull String key) throws ApiException {
    return getSingleMessage(key, null);
  }

  /**
   * Get single message from a mailbox
   * Retrieves a single message from the specified mailbox. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @param headers Optional headers to include in the request
   * @return MessageViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageViewModel getSingleMessage(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageViewModel> localVarResponse = getSingleMessageWithHttpInfo(key, headers);
    return localVarResponse.getData();
  }

  /**
   * Get single message from a mailbox
   * Retrieves a single message from the specified mailbox. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @return ApiResponse&lt;MessageViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageViewModel> getSingleMessageWithHttpInfo(@jakarta.annotation.Nonnull String key) throws ApiException {
    return getSingleMessageWithHttpInfo(key, null);
  }

  /**
   * Get single message from a mailbox
   * Retrieves a single message from the specified mailbox. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageViewModel> getSingleMessageWithHttpInfo(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSingleMessageRequestBuilder(key, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSingleMessage", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageViewModel>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageViewModel responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageViewModel>() {});
        

        return new ApiResponse<MessageViewModel>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSingleMessageRequestBuilder(@jakarta.annotation.Nonnull String key, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getSingleMessage");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}/single"
        .replace("{key}", ApiClient.urlEncode(key.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

  /**
   * Get single message with template parsing
   * Retrieves a single message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @param template  (required)
   * @return MessageParsedViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageParsedViewModel getSingleMessageWithTemplate(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template) throws ApiException {
    return getSingleMessageWithTemplate(key, template, null);
  }

  /**
   * Get single message with template parsing
   * Retrieves a single message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @param template  (required)
   * @param headers Optional headers to include in the request
   * @return MessageParsedViewModel
   * @throws ApiException if fails to make API call
   */
  public MessageParsedViewModel getSingleMessageWithTemplate(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template, Map<String, String> headers) throws ApiException {
    ApiResponse<MessageParsedViewModel> localVarResponse = getSingleMessageWithTemplateWithHttpInfo(key, template, headers);
    return localVarResponse.getData();
  }

  /**
   * Get single message with template parsing
   * Retrieves a single message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @param template  (required)
   * @return ApiResponse&lt;MessageParsedViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageParsedViewModel> getSingleMessageWithTemplateWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template) throws ApiException {
    return getSingleMessageWithTemplateWithHttpInfo(key, template, null);
  }

  /**
   * Get single message with template parsing
   * Retrieves a single message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox contains 0 or more than 1 message.
   * @param key  (required)
   * @param template  (required)
   * @param headers Optional headers to include in the request
   * @return ApiResponse&lt;MessageParsedViewModel&gt;
   * @throws ApiException if fails to make API call
   */
  public ApiResponse<MessageParsedViewModel> getSingleMessageWithTemplateWithHttpInfo(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template, Map<String, String> headers) throws ApiException {
    HttpRequest.Builder localVarRequestBuilder = getSingleMessageWithTemplateRequestBuilder(key, template, headers);
    try {
      HttpResponse<InputStream> localVarResponse = memberVarHttpClient.send(
          localVarRequestBuilder.build(),
          HttpResponse.BodyHandlers.ofInputStream());
      if (memberVarResponseInterceptor != null) {
        memberVarResponseInterceptor.accept(localVarResponse);
      }
      InputStream localVarResponseBody = null;
      try {
        if (localVarResponse.statusCode()/ 100 != 2) {
          throw getApiException("getSingleMessageWithTemplate", localVarResponse);
        }
        localVarResponseBody = ApiClient.getResponseBody(localVarResponse);
        if (localVarResponseBody == null) {
          return new ApiResponse<MessageParsedViewModel>(
              localVarResponse.statusCode(),
              localVarResponse.headers().map(),
              null
          );
        }

        
        
        String responseBody = new String(localVarResponseBody.readAllBytes());
        MessageParsedViewModel responseValue = responseBody.isBlank()? null: memberVarObjectMapper.readValue(responseBody, new TypeReference<MessageParsedViewModel>() {});
        

        return new ApiResponse<MessageParsedViewModel>(
            localVarResponse.statusCode(),
            localVarResponse.headers().map(),
            responseValue
        );
      } finally {
        if (localVarResponseBody != null) {
          localVarResponseBody.close();
        }
      }
    } catch (IOException e) {
      throw new ApiException(e);
    }
    catch (InterruptedException e) {
      Thread.currentThread().interrupt();
      throw new ApiException(e);
    }
  }

  private HttpRequest.Builder getSingleMessageWithTemplateRequestBuilder(@jakarta.annotation.Nonnull String key, @jakarta.annotation.Nonnull String template, Map<String, String> headers) throws ApiException {
    // verify the required parameter 'key' is set
    if (key == null) {
      throw new ApiException(400, "Missing the required parameter 'key' when calling getSingleMessageWithTemplate");
    }
    // verify the required parameter 'template' is set
    if (template == null) {
      throw new ApiException(400, "Missing the required parameter 'template' when calling getSingleMessageWithTemplate");
    }

    HttpRequest.Builder localVarRequestBuilder = HttpRequest.newBuilder();

    String localVarPath = "/messages/{key}/{template}/single"
        .replace("{key}", ApiClient.urlEncode(key.toString()))
        .replace("{template}", ApiClient.urlEncode(template.toString()));

    localVarRequestBuilder.uri(URI.create(memberVarBaseUri + localVarPath));

    localVarRequestBuilder.header("Accept", "application/json, application/problem+json");

    localVarRequestBuilder.method("GET", HttpRequest.BodyPublishers.noBody());
    if (memberVarReadTimeout != null) {
      localVarRequestBuilder.timeout(memberVarReadTimeout);
    }
    // Add custom headers if provided
    localVarRequestBuilder = HttpRequestBuilderExtensions.withAdditionalHeaders(localVarRequestBuilder, headers);
    if (memberVarInterceptor != null) {
      memberVarInterceptor.accept(localVarRequestBuilder);
    }
    return localVarRequestBuilder;
  }

}
