/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MailboxCreateModel
 */
class MailboxCreateModelTest {
    private final MailboxCreateModel model = new MailboxCreateModel();

    /**
     * Model tests for MailboxCreateModel
     */
    @Test
    void testMailboxCreateModel() {
        // TODO: test MailboxCreateModel
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'projectName'
     */
    @Test
    void projectNameTest() {
        // TODO: test projectName
    }

    /**
     * Test the property 'isTemporary'
     */
    @Test
    void isTemporaryTest() {
        // TODO: test isTemporary
    }

}
