/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for MessageViewModel
 */
class MessageViewModelTest {
    private final MessageViewModel model = new MessageViewModel();

    /**
     * Model tests for MessageViewModel
     */
    @Test
    void testMessageViewModel() {
        // TODO: test MessageViewModel
    }

    /**
     * Test the property 'uniqueId'
     */
    @Test
    void uniqueIdTest() {
        // TODO: test uniqueId
    }

    /**
     * Test the property 'from'
     */
    @Test
    void fromTest() {
        // TODO: test from
    }

    /**
     * Test the property 'to'
     */
    @Test
    void toTest() {
        // TODO: test to
    }

    /**
     * Test the property 'cc'
     */
    @Test
    void ccTest() {
        // TODO: test cc
    }

    /**
     * Test the property 'bcc'
     */
    @Test
    void bccTest() {
        // TODO: test bcc
    }

    /**
     * Test the property 'subject'
     */
    @Test
    void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'isHtml'
     */
    @Test
    void isHtmlTest() {
        // TODO: test isHtml
    }

    /**
     * Test the property 'received'
     */
    @Test
    void receivedTest() {
        // TODO: test received
    }

}
