/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.devinbox.client.ApiClient;
/**
 * MailboxCreateModel
 */
@JsonPropertyOrder({
  MailboxCreateModel.JSON_PROPERTY_NAME,
  MailboxCreateModel.JSON_PROPERTY_PROJECT_NAME,
  MailboxCreateModel.JSON_PROPERTY_IS_TEMPORARY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-29T16:01:12.920188793Z[Etc/UTC]", comments = "Generator version: 7.18.0")
public class MailboxCreateModel {
  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_PROJECT_NAME = "projectName";
  @jakarta.annotation.Nullable
  private String projectName;

  public static final String JSON_PROPERTY_IS_TEMPORARY = "isTemporary";
  @jakarta.annotation.Nullable
  private Boolean isTemporary = true;

  public MailboxCreateModel() { 
  }

  public MailboxCreateModel name(@jakarta.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Optional name for the mailbox. If not provided, a temporary mailbox will be created.
   * @return name
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nullable String name) {
    this.name = name;
  }


  public MailboxCreateModel projectName(@jakarta.annotation.Nullable String projectName) {
    this.projectName = projectName;
    return this;
  }

  /**
   * Name of the project to associate the mailbox with. If not provided, uses the default project.
   * @return projectName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProjectName() {
    return projectName;
  }


  @JsonProperty(value = JSON_PROPERTY_PROJECT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProjectName(@jakarta.annotation.Nullable String projectName) {
    this.projectName = projectName;
  }


  public MailboxCreateModel isTemporary(@jakarta.annotation.Nullable Boolean isTemporary) {
    this.isTemporary = isTemporary;
    return this;
  }

  /**
   * Whether the mailbox should be temporary or persistent.
   * @return isTemporary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_IS_TEMPORARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsTemporary() {
    return isTemporary;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_TEMPORARY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsTemporary(@jakarta.annotation.Nullable Boolean isTemporary) {
    this.isTemporary = isTemporary;
  }


  /**
   * Return true if this MailboxCreateModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailboxCreateModel mailboxCreateModel = (MailboxCreateModel) o;
    return Objects.equals(this.name, mailboxCreateModel.name) &&
        Objects.equals(this.projectName, mailboxCreateModel.projectName) &&
        Objects.equals(this.isTemporary, mailboxCreateModel.isTemporary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, projectName, isTemporary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailboxCreateModel {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    projectName: ").append(toIndentedString(projectName)).append("\n");
    sb.append("    isTemporary: ").append(toIndentedString(isTemporary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `projectName` to the URL query string
    if (getProjectName() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sprojectName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProjectName()))));
    }

    // add `isTemporary` to the URL query string
    if (getIsTemporary() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisTemporary%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsTemporary()))));
    }

    return joiner.toString();
  }
}

