/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.devinbox.client.model.MessageCountResultCount;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.devinbox.client.ApiClient;
/**
 * MessageCountResult
 */
@JsonPropertyOrder({
  MessageCountResult.JSON_PROPERTY_KEY,
  MessageCountResult.JSON_PROPERTY_COUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-16T13:41:55.031816651Z[Etc/UTC]", comments = "Generator version: 7.18.0")
public class MessageCountResult {
  public static final String JSON_PROPERTY_KEY = "key";
  @javax.annotation.Nonnull
  private String key;

  public static final String JSON_PROPERTY_COUNT = "count";
  @javax.annotation.Nonnull
  private MessageCountResultCount count;

  public MessageCountResult() { 
  }

  public MessageCountResult key(@javax.annotation.Nonnull String key) {
    this.key = key;
    return this;
  }

  /**
   * Mailbox unique identifier
   * @return key
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getKey() {
    return key;
  }


  @JsonProperty(value = JSON_PROPERTY_KEY, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(@javax.annotation.Nonnull String key) {
    this.key = key;
  }


  public MessageCountResult count(@javax.annotation.Nonnull MessageCountResultCount count) {
    this.count = count;
    return this;
  }

  /**
   * Get count
   * @return count
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public MessageCountResultCount getCount() {
    return count;
  }


  @JsonProperty(value = JSON_PROPERTY_COUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCount(@javax.annotation.Nonnull MessageCountResultCount count) {
    this.count = count;
  }


  /**
   * Return true if this MessageCountResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageCountResult messageCountResult = (MessageCountResult) o;
    return Objects.equals(this.key, messageCountResult.key) &&
        Objects.equals(this.count, messageCountResult.count);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, count);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageCountResult {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `key` to the URL query string
    if (getKey() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%skey%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getKey()))));
    }

    // add `count` to the URL query string
    if (getCount() != null) {
      joiner.add(getCount().toUrlQueryString(prefix + "count" + suffix));
    }

    return joiner.toString();
  }
}

