/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import io.devinbox.client.ApiClient;
/**
 * MessageViewModel
 */
@JsonPropertyOrder({
  MessageViewModel.JSON_PROPERTY_UNIQUE_ID,
  MessageViewModel.JSON_PROPERTY_FROM,
  MessageViewModel.JSON_PROPERTY_TO,
  MessageViewModel.JSON_PROPERTY_CC,
  MessageViewModel.JSON_PROPERTY_BCC,
  MessageViewModel.JSON_PROPERTY_SUBJECT,
  MessageViewModel.JSON_PROPERTY_BODY,
  MessageViewModel.JSON_PROPERTY_IS_HTML,
  MessageViewModel.JSON_PROPERTY_RECEIVED
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-12-29T16:01:12.920188793Z[Etc/UTC]", comments = "Generator version: 7.18.0")
public class MessageViewModel {
  public static final String JSON_PROPERTY_UNIQUE_ID = "uniqueId";
  @jakarta.annotation.Nonnull
  private UUID uniqueId;

  public static final String JSON_PROPERTY_FROM = "from";
  @jakarta.annotation.Nullable
  private List<String> from;

  public static final String JSON_PROPERTY_TO = "to";
  @jakarta.annotation.Nullable
  private List<String> to;

  public static final String JSON_PROPERTY_CC = "cc";
  @jakarta.annotation.Nullable
  private List<String> cc;

  public static final String JSON_PROPERTY_BCC = "bcc";
  @jakarta.annotation.Nullable
  private List<String> bcc;

  public static final String JSON_PROPERTY_SUBJECT = "subject";
  @jakarta.annotation.Nullable
  private String subject;

  public static final String JSON_PROPERTY_BODY = "body";
  @jakarta.annotation.Nullable
  private String body;

  public static final String JSON_PROPERTY_IS_HTML = "isHtml";
  @jakarta.annotation.Nonnull
  private Boolean isHtml;

  public static final String JSON_PROPERTY_RECEIVED = "received";
  @jakarta.annotation.Nonnull
  private OffsetDateTime received;

  public MessageViewModel() { 
  }

  public MessageViewModel uniqueId(@jakarta.annotation.Nonnull UUID uniqueId) {
    this.uniqueId = uniqueId;
    return this;
  }

  /**
   * Unique identifier for the message
   * @return uniqueId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_UNIQUE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public UUID getUniqueId() {
    return uniqueId;
  }


  @JsonProperty(value = JSON_PROPERTY_UNIQUE_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUniqueId(@jakarta.annotation.Nonnull UUID uniqueId) {
    this.uniqueId = uniqueId;
  }


  public MessageViewModel from(@jakarta.annotation.Nullable List<String> from) {
    this.from = from;
    return this;
  }

  public MessageViewModel addFromItem(String fromItem) {
    if (this.from == null) {
      this.from = new ArrayList<>();
    }
    this.from.add(fromItem);
    return this;
  }

  /**
   * Array of sender email addresses
   * @return from
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getFrom() {
    return from;
  }


  @JsonProperty(value = JSON_PROPERTY_FROM, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFrom(@jakarta.annotation.Nullable List<String> from) {
    this.from = from;
  }


  public MessageViewModel to(@jakarta.annotation.Nullable List<String> to) {
    this.to = to;
    return this;
  }

  public MessageViewModel addToItem(String toItem) {
    if (this.to == null) {
      this.to = new ArrayList<>();
    }
    this.to.add(toItem);
    return this;
  }

  /**
   * Array of recipient email addresses
   * @return to
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getTo() {
    return to;
  }


  @JsonProperty(value = JSON_PROPERTY_TO, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTo(@jakarta.annotation.Nullable List<String> to) {
    this.to = to;
  }


  public MessageViewModel cc(@jakarta.annotation.Nullable List<String> cc) {
    this.cc = cc;
    return this;
  }

  public MessageViewModel addCcItem(String ccItem) {
    if (this.cc == null) {
      this.cc = new ArrayList<>();
    }
    this.cc.add(ccItem);
    return this;
  }

  /**
   * Array of CC email addresses
   * @return cc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CC, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getCc() {
    return cc;
  }


  @JsonProperty(value = JSON_PROPERTY_CC, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCc(@jakarta.annotation.Nullable List<String> cc) {
    this.cc = cc;
  }


  public MessageViewModel bcc(@jakarta.annotation.Nullable List<String> bcc) {
    this.bcc = bcc;
    return this;
  }

  public MessageViewModel addBccItem(String bccItem) {
    if (this.bcc == null) {
      this.bcc = new ArrayList<>();
    }
    this.bcc.add(bccItem);
    return this;
  }

  /**
   * Array of BCC email addresses
   * @return bcc
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BCC, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<String> getBcc() {
    return bcc;
  }


  @JsonProperty(value = JSON_PROPERTY_BCC, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBcc(@jakarta.annotation.Nullable List<String> bcc) {
    this.bcc = bcc;
  }


  public MessageViewModel subject(@jakarta.annotation.Nullable String subject) {
    this.subject = subject;
    return this;
  }

  /**
   * Email subject line
   * @return subject
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSubject() {
    return subject;
  }


  @JsonProperty(value = JSON_PROPERTY_SUBJECT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSubject(@jakarta.annotation.Nullable String subject) {
    this.subject = subject;
  }


  public MessageViewModel body(@jakarta.annotation.Nullable String body) {
    this.body = body;
    return this;
  }

  /**
   * Email body content
   * @return body
   */
  @jakarta.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBody() {
    return body;
  }


  @JsonProperty(value = JSON_PROPERTY_BODY, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBody(@jakarta.annotation.Nullable String body) {
    this.body = body;
  }


  public MessageViewModel isHtml(@jakarta.annotation.Nonnull Boolean isHtml) {
    this.isHtml = isHtml;
    return this;
  }

  /**
   * Whether the email body is HTML format
   * @return isHtml
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_IS_HTML, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsHtml() {
    return isHtml;
  }


  @JsonProperty(value = JSON_PROPERTY_IS_HTML, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsHtml(@jakarta.annotation.Nonnull Boolean isHtml) {
    this.isHtml = isHtml;
  }


  public MessageViewModel received(@jakarta.annotation.Nonnull OffsetDateTime received) {
    this.received = received;
    return this;
  }

  /**
   * Timestamp when the message was received
   * @return received
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RECEIVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OffsetDateTime getReceived() {
    return received;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIVED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setReceived(@jakarta.annotation.Nonnull OffsetDateTime received) {
    this.received = received;
  }


  /**
   * Return true if this MessageViewModel object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MessageViewModel messageViewModel = (MessageViewModel) o;
    return Objects.equals(this.uniqueId, messageViewModel.uniqueId) &&
        Objects.equals(this.from, messageViewModel.from) &&
        Objects.equals(this.to, messageViewModel.to) &&
        Objects.equals(this.cc, messageViewModel.cc) &&
        Objects.equals(this.bcc, messageViewModel.bcc) &&
        Objects.equals(this.subject, messageViewModel.subject) &&
        Objects.equals(this.body, messageViewModel.body) &&
        Objects.equals(this.isHtml, messageViewModel.isHtml) &&
        Objects.equals(this.received, messageViewModel.received);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uniqueId, from, to, cc, bcc, subject, body, isHtml, received);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MessageViewModel {\n");
    sb.append("    uniqueId: ").append(toIndentedString(uniqueId)).append("\n");
    sb.append("    from: ").append(toIndentedString(from)).append("\n");
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    cc: ").append(toIndentedString(cc)).append("\n");
    sb.append("    bcc: ").append(toIndentedString(bcc)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    body: ").append(toIndentedString(body)).append("\n");
    sb.append("    isHtml: ").append(toIndentedString(isHtml)).append("\n");
    sb.append("    received: ").append(toIndentedString(received)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `uniqueId` to the URL query string
    if (getUniqueId() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%suniqueId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUniqueId()))));
    }

    // add `from` to the URL query string
    if (getFrom() != null) {
      for (int i = 0; i < getFrom().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sfrom%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getFrom().get(i)))));
      }
    }

    // add `to` to the URL query string
    if (getTo() != null) {
      for (int i = 0; i < getTo().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sto%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getTo().get(i)))));
      }
    }

    // add `cc` to the URL query string
    if (getCc() != null) {
      for (int i = 0; i < getCc().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%scc%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getCc().get(i)))));
      }
    }

    // add `bcc` to the URL query string
    if (getBcc() != null) {
      for (int i = 0; i < getBcc().size(); i++) {
        joiner.add(String.format(java.util.Locale.ROOT, "%sbcc%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getBcc().get(i)))));
      }
    }

    // add `subject` to the URL query string
    if (getSubject() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%ssubject%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getSubject()))));
    }

    // add `body` to the URL query string
    if (getBody() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sbody%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBody()))));
    }

    // add `isHtml` to the URL query string
    if (getIsHtml() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sisHtml%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsHtml()))));
    }

    // add `received` to the URL query string
    if (getReceived() != null) {
      joiner.add(String.format(java.util.Locale.ROOT, "%sreceived%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getReceived()))));
    }

    return joiner.toString();
  }
}

