/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.api;

import io.devinbox.client.ApiException;
import io.devinbox.client.model.MailboxCreateModel;
import io.devinbox.client.model.MailboxViewModel;
import io.devinbox.client.model.ProblemDetails;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MailboxesApi
 */
@Disabled
public class MailboxesApiTest {

    private final MailboxesApi api = new MailboxesApi();

    
    /**
     * Create a new mailbox
     *
     * Creates a new mailbox for receiving test emails. Can be temporary or persistent.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createMailboxTest() throws ApiException {
        MailboxCreateModel mailboxCreateModel = null;
        MailboxViewModel response = 
        api.createMailbox(mailboxCreateModel);
        
        // TODO: test validations
    }
    
}
