/*
 * DevInbox.ApiService | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@devinbox.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.devinbox.client.api;

import io.devinbox.client.ApiException;
import io.devinbox.client.model.GetMessagesSkipParameter;
import io.devinbox.client.model.MessageCountResult;
import io.devinbox.client.model.MessageParsedViewModel;
import io.devinbox.client.model.MessageViewModel;
import io.devinbox.client.model.MessagesViewModel;
import io.devinbox.client.model.ProblemDetails;
import java.util.UUID;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for MessagesApi
 */
@Disabled
public class MessagesApiTest {

    private final MessagesApi api = new MessagesApi();

    
    /**
     * Get the last message from a mailbox
     *
     * Retrieves the most recent message from the specified mailbox. Returns an error if the mailbox is empty.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLastMessageTest() throws ApiException {
        String key = null;
        MessageViewModel response = 
        api.getLastMessage(key);
        
        // TODO: test validations
    }
    
    /**
     * Get the last message with template parsing
     *
     * Retrieves the most recent message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox is empty.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getLastMessageWithTemplateTest() throws ApiException {
        String key = null;
        String template = null;
        MessageParsedViewModel response = 
        api.getLastMessageWithTemplate(key, template);
        
        // TODO: test validations
    }
    
    /**
     * Get a specific message by ID
     *
     * Retrieves a specific message from the specified mailbox using its unique ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageByIdTest() throws ApiException {
        String key = null;
        UUID id = null;
        MessageViewModel response = 
        api.getMessageById(key, id);
        
        // TODO: test validations
    }
    
    /**
     * Get message count for a mailbox
     *
     * Returns the total number of messages in the specified mailbox.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessageCountTest() throws ApiException {
        String key = null;
        MessageCountResult response = 
        api.getMessageCount(key);
        
        // TODO: test validations
    }
    
    /**
     * Get messages from a mailbox
     *
     * Retrieves messages from the specified mailbox with optional pagination. Default: skip&#x3D;0, take&#x3D;10, max take&#x3D;25.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getMessagesTest() throws ApiException {
        String key = null;
        GetMessagesSkipParameter skip = null;
        GetMessagesSkipParameter take = null;
        MessagesViewModel response = 
        api.getMessages(key, skip, take);
        
        // TODO: test validations
    }
    
    /**
     * Get single message from a mailbox
     *
     * Retrieves a single message from the specified mailbox. Returns an error if the mailbox contains 0 or more than 1 message.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSingleMessageTest() throws ApiException {
        String key = null;
        MessageViewModel response = 
        api.getSingleMessage(key);
        
        // TODO: test validations
    }
    
    /**
     * Get single message with template parsing
     *
     * Retrieves a single message from the specified mailbox and parses it using the provided template. Returns an error if the mailbox contains 0 or more than 1 message.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getSingleMessageWithTemplateTest() throws ApiException {
        String key = null;
        String template = null;
        MessageParsedViewModel response = 
        api.getSingleMessageWithTemplate(key, template);
        
        // TODO: test validations
    }
    
}
